### ISSUE TITLE
Something possibly wrong with stylelint?

### ISSUE THREAD

**Issue by sethidden** [sethidden/vue3-eslint-stylelint-demo#1]
Just noticed this comment https://github.com/johnsoncodehk/volar/issues/725#issuecomment-977764422 , guess I need to add some stuff to the stylelint config? Will have to take a closer look later

**Comment by gusleindecker** [comment]
I used your demo project and managed to make stylelint and prettier to work as I wanted. For that what I did was:

1. Rename the `.stylelintrc.js` file to `stylelint.config.js`;
2. Change the contents of the `stylelint.config.js` file to
    ```
    module.exports = {
      extends: ['stylelint-config-recommended-vue', 'stylelint-config-prettier'],
    };
    ```
3. Add the `stylelint.validate` property in the workspace settings for vscode (`./.vscode/settings.json`) like this
    ```
    {
      "stylelint.validate": ["vue"],
    }
    ```
I hope this helps

**Comment by sethidden** [comment]
I added your changes in 502ee689a719e3aa4f4ba9ec52a34300a980d3c3 and 327c9b6782f477e80efb7802c1ded32cb59f125b

I kept the .stylelintrc.js since most other config files in the repo root are .*rc.js

Thanks for the stylelint.validate tip especially :)
